FROM ghcr.io/kalavai-net/ray-base:latest AS base

FROM nvidia/cuda:12.9.2-devel-ubuntu24.04
#FROM nvidia/cuda:13.0.0-devel-ubuntu24.04
#FROM rayproject/ray:2.54.1-py312-cu129

ARG PIP_VLLM_VERSION=0.14.0
WORKDIR /home/ray/workspace

# copy over ray scripts
COPY --from=base /home/ray/workspace/ .

RUN apt update && apt install bc wget ffmpeg curl python3-dev python3 python3-pip python3-venv git  -y && \
    rm -rf /var/lib/apt/lists/*

# install dependencies
COPY common_requirements.txt .

RUN python3 -m venv /home/ray/workspace/env

RUN . /home/ray/workspace/env/bin/activate && \
    pip install -r common_requirements.txt --no-cache-dir

RUN . /home/ray/workspace/env/bin/activate && \
    pip install vllm[audio,video]==$PIP_VLLM_VERSION --no-cache-dir

# vllm-omni from source to ensure version compatibility
RUN . /home/ray/workspace/env/bin/activate && \
    git clone https://github.com/vllm-project/vllm-omni.git && \
    cd vllm-omni && \
    pip install -e .

# Voxtral / Gemma 4 issue (might be solved in >0.22.1)
# Also seems to make inference faster for Quen3.6 35B?
# RUN . /home/ray/workspace/env/bin/activate && \
#     pip install --force-reinstall "transformers==5.9.0" --no-cache-dir

COPY run_model.sh .
RUN chmod +x /home/ray/workspace/run_model.sh

ENTRYPOINT [ "/bin/bash" ]