FROM ghcr.io/kalavai-net/ray-base:latest AS base

FROM rayproject/ray:2.51.0.2f4360-py312-cu124

ARG PIP_VLLM_VERSION=0.15.1
WORKDIR /home/ray/workspace

RUN sudo apt update && sudo apt install --no-install-recommends \
    bc wget ffmpeg curl -y && \
    sudo rm -rf /var/lib/apt/lists/*

# copy over scripts
COPY --from=base /home/ray/workspace/ .
COPY common_requirements.txt .
COPY run_model.sh .

#pip3 install lmcache --prefer-binary --no-cache-dir && \
# reinstalling Ray after vllm so we pin the version and submodules (otherwise vllm brings its own)
#RUN python3 -m venv /home/ray/workspace/env
#RUN . /home/ray/workspace/env/bin/activate && \
RUN pip install --no-cache-dir -r common_requirements.txt
RUN pip install --no-cache-dir vllm==$PIP_VLLM_VERSION

# install torchdec https://github.com/QwenLM/Qwen2.5-VL?tab=readme-ov-file#installing-cuda-enabled-torchcodec 
#pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --no-cache-dir && \
#RUN . /home/ray/workspace/env/bin/activate && \
RUN pip install --no-cache-dir torchcodec --index-url=https://download.pytorch.org/whl/cu124

RUN sudo chmod +x /home/ray/workspace/run_model.sh

ENTRYPOINT [ "/bin/bash" ]