hfToken: null

llamacpp:
  repoId: null
  quant: null
  serverExtra: null
  imagePullPolicy: IfNotPresent
  version: b8941-1
  restartPolicy: OnFailure

lago:
  enabled: false
  apiKey: null
  eventCode: null
  eventInterval: null
  externalSubscriptionId: null
  url: null

litellm:
  enabled: false
  provider: openai
  waitReady: false
  modelNameOverride: null
  accessGroup: null
  baseUrl: null
  kalavaiExtras: '{}'
  key: null

system:
  jobId: null
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  nodeAffinityPreferenceKey: null
  envFromSecrets: {}
  workerGpuMemory: null
  backend: cpu
  workers: 1
  workingMemory: 5
  cpus: 2
  memory: 8

ingress:
  enabled: false
  subdomain: spaces.kalavai.net