hfToken: null

llamacpp:
  repoId: null
  quant: null
  serverExtra: null
  imagePullPolicy: IfNotPresent
  version: b8941-1
  restartPolicy: Always

litellm:
  enabled: false
  provider: openai
  waitReady: false
  modelNameOverride: null
  accessGroup: null
  baseUrl: null
  kalavaiExtras: '{}'
  key: null

billing:
  enabled: false
  interval: 60
  userId: ""

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 1

loadBalancer:
  enabled: true
  trafficPolicy: LEAST_REQUEST

service:
  stickySession: false
  stickySessionTimeoutSeconds: 3600
  ingress:
    enabled: false
    subdomain: spaces.kalavai.net

system:
  jobId: null
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  nodeAffinityPreferenceKey: null
  envFromSecrets: {}
  
resources:
  replicas: 1
  workers: 1
  workerGpuMemory: null
  backend: cpu
  workingMemory: 5
  cpus: 2
  memory: 8
  gpus: 1
