apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-deployer-secrets
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
type: Opaque
stringData:
  deployer_master_key: {{ .Values.deployer.masterApiKey | quote }}
  kalavai_api_key: {{ .Values.deployer.kalavaiApi.key | quote }}
  litellm_ui_username: {{ .Values.deployer.gateway.ui_username | quote }}
  litellm_ui_password: {{ .Values.deployer.gateway.ui_password | quote }}
  litellm_key: {{ .Values.deployer.gateway.litellm_key | quote }}