apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-deployer-secrets
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
type: Opaque
stringData:
  deployer_master_key: {{ .Values.deployer.masterApiKey | quote }}
  kalavai_api_key: {{ .Values.deployer.kalavaiApiKey | quote }}
  litellm_key: {{ randAlphaNum 32 | quote }}
  litellm_salt_key: {{ randAlphaNum 32 | quote }}
  litellm_ui_password: {{ .Values.litellm.litellm_ui_password | quote }}
  litellm_db_password: {{ randAlphaNum 32 | quote }}