# Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-litellm
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
    component: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
      component: litellm
  template:
    metadata:
      labels:
        kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
        component: litellm
        role: leader
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.system.priorityClassName }}
      priorityClassName: {{ .Values.system.priorityClassName }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unknown"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/memory-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/disk-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/pid-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/network-unavailable"
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kalavai.job.name
                  operator: In
                  values:
                  - {{ .Values.system.jobId | default .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{- if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{- range $v }}
                - "{{ . }}"
                {{- end }}
            {{ end }}
          {{- else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{- end }}
      {{- end }}
      containers:
      - name: service
        image: "litellm/litellm:v1.83.3-stable"
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          DB_HOST={{ .Release.Name }}-gateway-db-service:5432;
          export DATABASE_URL=postgres://admin:$POSTGRES_PASSWORD@$DB_HOST/litellm
          litellm --port 4000 --config /workspace/config.yaml
        env:
        {{- if .Values.system.envFromSecrets }}
        {{- range .Values.system.envFromSecrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: {{ . }}
        {{- end }}
        {{- end }}
        - name: LITELLM_LOG
          value: ERROR
        - name: LITELLM_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name }}-gateway-secret
              key: litellm_key
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name }}-gateway-secret
              key: db_password
        - name: LITELLM_SALT_KEY
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name }}-gateway-secret
              key: litellm_salt_key
        - name: STORE_MODEL_IN_DB
          value: "True"
        - name: PORT
          value: "4000"
        - name: UI_USERNAME
          value: {{ .Values.litellm.ui_username | quote }}
        - name: UI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name }}-gateway-secret
              key: litellm_ui_password
        ports:
        - containerPort: 4000
          name: container-port
        resources:
          requests:
            cpu: 1
            memory: 1.5Gi
          limits:
            cpu: 1
            memory: 1.5Gi
        volumeMounts:
        - name: config-volume
          mountPath: /workspace/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-gateway-config
      restartPolicy: Always
---
# Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-db
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
      component: db
  template:
    metadata:
      labels:
        kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
        component: db
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.system.priorityClassName }}
      priorityClassName: {{ .Values.system.priorityClassName }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unknown"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/memory-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/disk-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/pid-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/network-unavailable"
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kalavai.job.name
                  operator: In
                  values:
                  - {{ .Values.system.jobId | default .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{- if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{- range $v }}
                - "{{ . }}"
                {{- end }}
            {{ end }}
          {{- else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{- end }}
      {{- end }}
      containers:
      - name: service
        image: "postgres:14"
        env:
        - name: POSTGRES_DB
          value: litellm
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-gateway-secret
              key: db_password
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        {{- if .Values.system.envFromSecrets }}
        {{- range .Values.system.envFromSecrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: {{ . }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 5432
          name: postgres-port
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
      restartPolicy: Always
---
{{- if .Values.ollama.enabled }}
# Ollama adaptor
# Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway-ollama
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
    component: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
      component: ollama
  template:
    metadata:
      labels:
        kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
        component: ollama
    spec:
      terminationGracePeriodSeconds: 10
      {{- if .Values.system.priorityClassName }}
      priorityClassName: {{ .Values.system.priorityClassName }}
      {{- end }}
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unreachable"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/unknown"
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 10
      - key: "node.kubernetes.io/memory-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/disk-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/pid-pressure"
        operator: Exists
        effect: NoSchedule
      - key: "node.kubernetes.io/network-unavailable"
        operator: Exists
        effect: NoSchedule
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: kalavai.job.name
                  operator: In
                  values:
                  - {{ .Values.system.jobId | default .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{- if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{- range $v }}
                - "{{ . }}"
                {{- end }}
            {{ end }}
          {{- else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{- end }}
      {{- end }}
      containers:
      - name: service
        image: "eyalrot2/ollama-openai-proxy:latest"
        env:
        - name: OPENAI_API_BASE_URL
          value: http://{{ .Release.Name }}-gateway-service:4000
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-gateway-secret
              key: litellm_key
        {{- if .Values.system.envFromSecrets }}
        {{- range .Values.system.envFromSecrets }}
        - name: {{ . }}
          valueFrom:
            secretKeyRef:
              name: {{ . }}
              key: {{ . }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 11434
          name: ollama-port
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      restartPolicy: Always
{{- end }}
