apiVersion: v1
stringData:
  litellm_key: {{ .Values.litellm.master_key | quote }}
  litellm_salt_key: {{ .Values.litellm.salt_key | quote }}
  litellm_ui_password: {{ .Values.litellm.ui_password | quote }}
  db_password: {{ randAlphaNum 32 | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-gateway-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true
