apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-db-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  selector:
    component: db
    kalavai.job.name: {{ .Values.system.jobId }}
  ports:
    - name: main
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  selector:
    component: litellm
    kalavai.job.name: {{ .Values.system.jobId }}
  ports:
    - name: main
      port: 4000
      targetPort: 4000
      protocol: TCP
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
---
{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-ollama-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  selector:
    component: ollama
    kalavai.job.name: {{ .Values.system.jobId }}
  ports:
    - name: main
      port: 11434
      targetPort: 11434
      protocol: TCP
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
{{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-large-body@kubernetescrd"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-gateway-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-gateway.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-gateway-service
            port:
              number: 4000 # match internal port
        path: /
        pathType: Prefix
---
{{- if .Values.ollama.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-large-body@kubernetescrd"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-gateway-ollama-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-gateway-ollama.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-gateway-ollama-service
            port:
              number: 11434 # match internal port
        path: /
        pathType: Prefix
{{- end }}
{{- end }}
