apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-inference-service
  labels:
    # must have this!
    kalavai.job.name: {{ .Values.system.jobId}}
spec:
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
  selector:
    role: leader
    kalavai.job.name: {{ .Values.system.jobId}}
  ports:
    - name: client
      port: 10001
      targetPort: 10001
      protocol: TCP
    - name: dashboard
      port: 8265
      targetPort: 8265
      protocol: TCP
    - name: serve
      port: 8000
      targetPort: 8000
      protocol: TCP
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-large-body@kubernetescrd"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-inference-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-inference.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-inference-service
            port:
              number: 8265 # Dashboard port
        path: /dashboard
        pathType: Prefix
      - backend:
          service:
            name: {{ .Release.Name }}-inference-service
            port:
              number: 8000 # Serve port
        path: /serve
        pathType: Prefix
{{- end }}