apiVersion: v1
stringData:
  hf_token: {{ .Values.hfToken }}
{{- if .Values.litellm.enabled }}
  litellm_key: {{ .Values.litellm.key }}
{{- end }}
{{- if .Values.billing.enabled }}
  billing_api_key: {{ .Values.billing.apiKey }}
{{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-llamacpp-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true