apiVersion: v1
stringData:
  hf_token: {{ .Values.llamacpp.hfToken }}
  litellm_key: {{ .Values.litellm.key }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-llamacpp-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true