apiVersion: kalavai.net/v1
kind: ServerWorkerSet
metadata:
  name: {{ .Release.Name }}-llamacpp
spec:
  replicas: {{ .Values.system.replicas }}
  workersPerInstance: {{ sub .Values.system.workers 1 }}
  labels:
    kalavai.job.name: {{ .Values.system.jobId}}
    {{- if .Values.system.workerGpuMemory }}
    kalavai/vram: {{ .Values.system.workerGpuMemory | quote }}
    {{- end }}
  service:
    name: {{ .Release.Name }}-llamacpp-service
    port: 8080           
    targetPort: 8080     
    stickySession: {{ .Values.service.stickySession }}
    stickySessionTimeoutSeconds: {{ .Values.service.stickySessionTimeoutSeconds }}
  {{- if .Values.service.ingress.enabled }}
    type: ClusterIP
  {{- else }}
    type: NodePort
  {{- end }}  
  autoScaling:
    enabled: {{ .Values.autoscaling.enabled }}
  {{- if .Values.autoscaling.enabled }}   
    hosts:
      - {{ .Release.Name }}-{{ .Release.Namespace }}-llamacpp.{{ .Values.service.ingress.subdomain }}   
    pathPrefixes:
      - "/"              
    replicas:
      min: {{ .Values.autoscaling.minReplicas }}        
      max: {{ .Values.autoscaling.maxReplicas }}
    scaledownPeriod: 300
    scalingMetric:
      requestRate:
        granularity: 1s
        targetValue: 1
        window: 1m
      # concurrency:
      #   targetValue: 10
  {{- end }}
{{- if .Values.litellm.enabled }}
  initHook:
    # Used for model registration
    spec:
      containers:
      - name: registrar-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. register model
          echo "REGISTER MODEL WITH GATEWAY..."
        {{- if .Values.litellm.waitReady }}
          echo "Waiting for model service to be up..."
          /workspace/wait_for_service.sh --servers="$GLOBAL_SERVICE_ADDRESS" --port=$GLOBAL_SERVICE_PORT
        {{- end }}
          export MODEL_API_BASE="http://$GLOBAL_SERVICE_ADDRESS:$GLOBAL_SERVICE_PORT/v1";
          /workspace/start_point.sh \
            --litellm_kalavai_extras='{{ .Values.litellm.kalavaiExtras }}' \
            --litellm_access_group={{ .Values.litellm.accessGroup }}
        env:
        - name: LITELLM_MODEL_NAME
        {{- if .Values.litellm.modelNameOverride }}
          value: "{{ .Values.litellm.modelNameOverride }}"
        {{- else }}
          {{- if .Values.llamacpp.quant }}
          value: "{{ .Values.llamacpp.repoId }}-{{ .Values.llamacpp.quant }}"
          {{- else }}
          value: "{{ .Values.llamacpp.repoId }}"
          {{- end }}
        {{- end }}
        - name: LITELLM_BASE_URL
          value: {{ .Values.litellm.baseUrl }}
        - name: LITELLM_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-llamacpp-secret
              key: litellm_key
        - name: MODEL_ID
        {{- if .Values.llamacpp.quant }}
          value: "{{ .Values.llamacpp.repoId }}-{{ .Values.llamacpp.quant }}"
        {{- else }}
          value: "{{ .Values.llamacpp.repoId }}"
        {{- end }}
        - name: DEPLOYMENT_ID
          value: {{ .Release.Name }}
        - name: PROVIDER
          value: {{ .Values.litellm.provider }}
  finalizerHook:
    # Used for model deregistration
    spec:
      containers:
      - name: registrar-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. deregister model
          /workspace/cleanup.sh
        env:
        - name: LITELLM_BASE_URL
          value: {{ .Values.litellm.baseUrl }}
        # secret may be deleted before this is run, so hardcode the key
        - name: LITELLM_KEY
          value: {{ .Values.litellm.key }}
        - name: DEPLOYMENT_ID
          value: {{ .Release.Name }}
{{- end }}
  server:
    spec:
      metadata:
        labels:
          billing: {{ .Values.billing.enabled | quote }}
      terminationGracePeriodSeconds: 60
    {{- if eq .Values.system.backend "cuda" }}
      runtimeClassName: nvidia
    {{- end }}
      affinity:
      {{- if .Values.system.nodeAffinityPreferenceKey }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  kalavai.job.name: {{ .Values.system.jobId }}
              topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
      {{- end }}
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{ if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{ range $v }}
                - "{{ . }}"
                {{ end }}
            {{ end }}
          {{ else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{ end }}
      {{- end }}
      {{- if .Values.billing.enabled }}
      serviceAccountName: kalavai-downstream-api-reader-sa
      {{- end }}
      containers:
      - name: llamacpp-leader
      {{ if eq .Values.system.backend "cuda" }}
        image: ghcr.io/kalavai-net/llamacpp-cuda:{{ .Values.llamacpp.version }}
      {{ else if eq .Values.system.backend "rocm" }}
        image: ghcr.io/kalavai-net/llamacpp-rocm:{{ .Values.llamacpp.version }}
      {{ else }}
        image: ghcr.io/kalavai-net/llamacpp-cpu:{{ .Values.llamacpp.version }}
      {{ end }}
        imagePullPolicy: {{ .Values.llamacpp.imagePullPolicy }}
        command:
        - sh
        - -c
        - |
          echo "Starting server..."
          # run model server
          export WORKERS=$(/workspace/get_workers_address.sh --rpc_port=50052 --rpc_servers="${WORKERS_ADDRESSES}")
          /workspace/run_api_server.sh \
            --repo_id={{ .Values.llamacpp.repoId }} \
            --quant={{ .Values.llamacpp.quant }} \
            --port=8080 \
            --rpc_servers=$WORKERS \
            --extra='{{ .Values.llamacpp.serverExtra}}'
        env:
        {{- range $key, $value := .Values.system.envFromSecrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $value }}
              key: {{ $key }}
        {{- end }}
        {{- if .Values.hfToken }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name}}-llamacpp-secret
              key: hf_token
        {{- end }}
        ports:
        - containerPort: 8080
          name: model-port
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: 1
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: 1
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
          limits:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: 1
            # {{ if .Values.system.workerGpuMemory }}
            # nvidia.com/gpumem: {{ .Values.system.workerGpuMemory}}
            # {{ end }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: 1
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
    {{- if .Values.billing.enabled }}  
      - name: billing-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. Fetch node Info
          echo "FETCH NODE INFO..."
          export PROVIDER=$(python3 get_node_label_value.py --in-cluster --node-name $NODE_NAME --label-key kalavai/region)
          export GPU_TYPE=$(python3 get_node_label_value.py --in-cluster --node-name $NODE_NAME --label-key kalavai/instance)
          echo "PROVIDER: $PROVIDER"
          echo "GPU_TYPE: $GPU_TYPE"

          # 2. Wait for model to be ready
          echo "WAIT FOR MODEL TO BE READY at $GLOBAL_SERVICE_ADDRESS:$GLOBAL_SERVICE_PORT..."
          /workspace/wait_for_service.sh --servers="$GLOBAL_SERVICE_ADDRESS" --port=$GLOBAL_SERVICE_PORT

          # 3. start heartbeat
          # VRAM USAGE / minute = billingInterval(mins) * gpuMemPerWorker  * NumWorkers
          {{- $vramAmount := mul (mul .Values.billing.interval .Values.system.workerGpuMemory) .Values.system.workers }}
          {{- $cpuAmount := mul (mul .Values.billing.interval .Values.system.cpus) .Values.system.workers }}
          {{- $memoryAmount := mul (mul .Values.billing.interval .Values.system.memory) .Values.system.workers }}
          echo "START HEARTBEAT..."
          python3 usage_event_generator.py
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: USER_ID
          value: {{ .Values.billing.userId }}
        - name: INTERVAL_SECONDS
          value: {{ .Values.billing.interval | quote }}
        - name: EVENT_TYPE
          value: usage
        - name: VRAM_AMOUNT
          value: {{ $vramAmount | quote }}
        - name: CPU_AMOUNT
          value: {{ $cpuAmount | quote }}
        - name: MEMORY_AMOUNT
          value: {{ $memoryAmount | quote }}
        - name: JOB_ID
          value: {{ .Values.system.jobId }}
        resources:
          requests:
            cpu: 0.05
            memory: 64Mi
          limits:
            cpu: 0.1
            memory: 128Mi
    {{- end }}
    policy:
    - event: PodFailed
      action: RestartInstance
    - event: OOMKilled
      action: RestartInstance
    - event: PodEvicted
      action: RestartInstance
    - event: Unknown
      action: RestartInstance
  worker:
    spec:
      terminationGracePeriodSeconds: 60
    {{- if eq .Values.system.backend "cuda" }}
      runtimeClassName: nvidia
    {{- end }}
      affinity:
      {{- if .Values.system.nodeAffinityPreferenceKey }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  kalavai.job.name: {{ .Values.system.jobId }}
              topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
      {{- end }}
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{ if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{ range $v }}
                - "{{ . }}"
                {{ end }}
            {{ end }}
          {{ else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{ end }}
      {{- end }}
      containers:
      - name: llamacpp-worker
      {{ if eq .Values.system.backend "cuda" }}
        image: ghcr.io/kalavai-net/llamacpp-cuda:{{ .Values.llamacpp.version }}
      {{ else if eq .Values.system.backend "rocm" }}
        image: ghcr.io/kalavai-net/llamacpp-rocm:{{ .Values.llamacpp.version }}
      {{ else }}
        image: ghcr.io/kalavai-net/llamacpp-cpu:{{ .Values.llamacpp.version }}
      {{ end }}
        imagePullPolicy: {{ .Values.llamacpp.imagePullPolicy }}
        command:
        - sh
        - -c
        - |
          /workspace/run_rpc_worker.sh --rpc_port=50052
        env:
        {{- range $key, $value := .Values.system.envFromSecrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $value }}
              key: {{ $key }}
        {{- end }}
        {{- if .Values.hfToken }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name}}-llamacpp-secret
              key: hf_token
        {{- end }}
        resources:
          requests:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: 1
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: 1
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
          limits:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: 1
            # {{ if .Values.system.workerGpuMemory }}
            # nvidia.com/gpumem: {{ .Values.system.workerGpuMemory}}
            # {{ end }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: 1
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
      restartPolicy: {{ .Values.llamacpp.restartPolicy }}
    policy:
    - event: PodFailed
      action: ReplacePod
    - event: OOMKilled
      action: ReplacePod
    - event: OOMKilled
      action: ReplacePod
    - event: PodEvicted
      action: ReplacePod
    - event: Unknown
      action: ReplacePod
---
{{- if .Values.service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-llamacpp-ingress
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-llamacpp.{{ .Values.service.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-llamacpp-service
            port:
              number: 8080 # match internal port
        path: /
        pathType: Prefix
{{- end }}