apiVersion: v1
stringData:
  hf_token: {{ .Values.hfToken }}
  p2p_token: {{ .Values.localai.p2pToken }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-localai-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true