modelId: null
hfToken: null

vllm:
  image:
    tag: v0.22.1-4
  forceVersion: null
  extra: --dtype float16 --enforce-eager
  loraModules: null
  templateUrl: null
  modelNameOverride: null
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  debugLevel: INFO
  autoParallelism: true
  sharedMemory: 3
  githubUsername: null
  githubToken: null

pip_installs: null

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 1

loadBalancer:
  enabled: true
  trafficPolicy: LEAST_REQUEST

service:
  stickySession: false
  stickySessionTimeoutSeconds: 3600
  ingress:
    enabled: false
    subdomain: spaces.kalavai.net

litellm:
  enabled: false
  provider: hosted_vllm
  waitReady: false
  modelNameOverride: null
  accessGroup: null
  baseUrl: null
  kalavaiExtras: '{}'
  key: null

lmcache:
  enabled: false
  chunkSize: 256
  localCpu: true
  localDisk: null
  maxLocalCpuSize: 3.0
  maxLocalDiskSize: 0
  remoteUrl: null
  kvTransferConfig: '{"kv_connector":"LMCacheConnectorV1","kv_role":"kv_both"}'

billing:
  enabled: false
  interval: 60
  userId: ""

system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null
  envFromSecrets: {}

resources:
  replicas: 1
  nodeAffinityPreferenceKey: null
  workerGpuMemory: null
  workers: 1
  backend: cuda
  workingMemory: 16
  memory: 8
  cpus: 4
  gpus: 1
