modelId: null
hfToken: null

vllm:
  image:
    tag: v0.20.1
  forceVersion: null
  extra: --dtype float16 --enforce-eager
  toolCallParser: llama3_json
  loraModules: null
  templateUrl: null
  modelNameOverride: null
  imagePullPolicy: IfNotPresent
  restartPolicy: Always
  debugLevel: INFO
  autoParallelism: true
  sharedMemory: 6
  githubUsername: null
  githubToken: null

autoscaling:
  enabled: false
  minReplicas: 0
  maxReplicas: 1

service:
  stickySession: true
  stickySessionTimeoutSeconds: 3600
  ingress:
    enabled: false
    subdomain: spaces.kalavai.net

litellm:
  enabled: false
  provider: hosted_vllm
  waitReady: false
  modelNameOverride: null
  accessGroup: null
  baseUrl: null
  kalavaiExtras: '{}'
  key: null

lmcache:
  chunkSize: 256
  localCpu: true
  localDisk: null
  maxLocalCpuSize: 5.0
  maxLocalDiskSize: 0
  remoteUrl: null

billing:
  enabled: false
  url: ""
  apiKey: ""
  eventName: ""
  interval: 0
  externalCustomerId: ""

system:
  queue: default
  replicas: 1
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null
  envFromSecrets: {}
  nodeAffinityPreferenceKey: null
  workerGpuMemory: null
  workers: 1
  backend: cuda
  workingMemory: 16
  memory: 8
  cpus: 4
  gpus: 1
