modelId: null
hfToken: null
workers: 1

vllm:
  image:
    tag: v0.18.1
  forceVersion: null
  extra: --dtype float16 --enforce-eager
  toolCallParser: llama3_json
  loraModules: null
  templateUrl: null

deployment:
  gpuBackend: cuda
  workingMemory: 16
  memory: 8
  sharedMemory: 6
  cpus: 4
  gpus: 1
  tensorParallelismOnly: false
  gpuMemory: null
  modelNameOverride: null
  imagePullPolicy: IfNotPresent
  debugLevel: INFO
  githubUsername: null
  githubToken: null

ingress:
  enabled: false
  subdomain: spaces.kalavai.net

litellm:
  enabled: false
  accessGroup: null
  baseUrl: http://litellm-service.default.svc.cluster.local:4000
  key: null
  kalavaiExtras: '{}'

lmcache:
  chunkSize: 256
  localCpu: true
  localDisk: null
  maxLocalCpuSize: 5.0
  maxLocalDiskSize: 0
  remoteUrl: null

lago:
  enabled: false
  apiKey: null
  eventCode: null
  eventInterval: null
  externalSubscriptionId: null
  url: null

system:
  queue: default
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null
