apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rstudio-secrets
  labels:
    kalavai.job.name: {{ .Values.system.jobId | default .Release.Name }}
type: Opaque
stringData:
  rstudio_password: {{ .Values.rstudio.password | quote }}