# {{- if .Values.imagePullSecrets }}
# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Release.Name}}-regcred
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.imagePullSecrets.registry .Values.imagePullSecrets.username .Values.imagePullSecrets.password .Values.imagePullSecrets.email (printf "%s:%s" .Values.imagePullSecrets.username .Values.imagePullSecrets.password | b64enc) | b64enc }}
# {{- end }}