apiVersion: v2
appVersion: 0.0.2
description: speaches is an OpenAI API-compatible server supporting streaming transcription,
  translation, and speech generation
icon: ''
kubeVersion: '>= 1.25.0'
maintainers:
- email: carlos@kalavai.net
  name: Carlos Fernandez Musoles
  url: https://kalavai.net
name: speaches
sources:
- https://speaches.ai/
version: 0.0.2
annotations:
  status: dev
  category: voice