speaches:
  model: speaches-ai/Kokoro-82M-v1.0-ONNX-int8

deployment:
  cpus: 2
  cudaGpuMemPercentage: 100
  gpuBackend: cuda
  gpus: 1
  memory: 4
litellm:
  accessGroup: null
  baseUrl: http://litellm.default.svc.cluster.local:4000
  enabled: false
  kalavaiExtras: '{}'
  key: null

system:
  jobId: null
  nodeSelectors: null
  nodeSelectorsOps: OR
  priorityClassName: user-spot-priority
  envFromSecrets: []
