speaches:
  model: speaches-ai/Kokoro-82M-v1.0-ONNX-int8

litellm:
  enabled: false
  provider: hosted_vllm
  waitReady: false
  modelNameOverride: null
  accessGroup: null
  baseUrl: null
  kalavaiExtras: '{}'
  key: null

system:
  jobId: null
  nodeSelectors: null
  nodeSelectorsOps: OR
  priorityClassName: user-spot-priority
  envFromSecrets: {}
  nodeAffinityPreferenceKey: null
  workerGpuMemory: null

resources:
  replicas: 1
  workerGpuMemory: null
  workers: 1
  backend: cuda
  workingMemory: 16
  memory: 8
  cpus: 2
  gpus: 1