FROM python:3.12-slim

RUN apt update --yes && \
    apt install --yes --no-install-recommends \
    # Common useful utilities
    build-essential \
    wget \
    curl \
    git \
    nano-tiny \
    tzdata \
    unzip \
    vim-tiny \
    # git-over-ssh
    openssh-client \
    # `less` is needed to run help in R
    # see: https://github.com/jupyter/docker-stacks/issues/1588
    less \
    # `nbconvert` dependencies
    # https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex
    texlive-xetex \
    texlive-fonts-recommended \
    texlive-plain-generic \
    # Enable clipboard on Linux host systems
    xclip && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Create kalavai user with proper home directory (this is the standard JupyterHub username)
RUN useradd -m -s /bin/bash kalavai && \
    mkdir -p /home/kalavai/.local && \
    chown -R kalavai:kalavai /home/kalavai

#USER kalavai
WORKDIR /home/kalavai

RUN python3 -m venv /home/kalavai/env

RUN . /home/kalavai/env/bin/activate && \
    pip install --no-cache-dir jupyterhub==5.4.3 jupyterlab jupyter-server-proxy[standalone]

# Set environment variables for the container session
ENV SHELL=/bin/bash
ENV PATH="/home/kalavai/env/bin:$PATH"

RUN echo "source /home/kalavai/env/bin/activate" >> ~/.bashrc

# set the default command of the image,
# if you want to launch more complex startup than the default `juptyerhub-singleuser`.
# To launch an image's custom CMD instead of the default `jupyterhub-singleuser`
# set `singleuser.cmd: null` in your config.yaml.
CMD ["jupyterhub-singleuser"]