FROM nvidia/cuda:13.0.0-devel-ubuntu24.04

RUN apt update && apt install python3-dev python3 python3-pip python3-venv -y && \
    rm -rf /var/lib/apt/lists/*

# Create kalavai user with proper home directory (this is the standard JupyterHub username)
RUN useradd -m -s /bin/bash kalavai && \
    mkdir -p /home/kalavai/.local && \
    chown -R kalavai:kalavai /home/kalavai

#USER kalavai
WORKDIR /home/kalavai

RUN python3 -m venv /home/kalavai/env

RUN . /home/kalavai/env/bin/activate && \
    pip install --no-cache-dir jupyterhub==5.4.3 jupyterlab jupyter-server-proxy[standalone]

# Set environment variables for the container session
ENV SHELL=/bin/bash
ENV PATH="/home/kalavai/env/bin:$PATH"

RUN echo "source /home/kalavai/env/bin/activate" >> ~/.bashrc

# set the default command of the image,
# if you want to launch more complex startup than the default `juptyerhub-singleuser`.
# To launch an image's custom CMD instead of the default `jupyterhub-singleuser`
# set `singleuser.cmd: null` in your config.yaml.
CMD ["jupyterhub-singleuser"]