apiVersion: v1
stringData:
  hf_token: {{ .Values.hfToken }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-personaplex-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true