apiVersion: v1
kind: Service
metadata:
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-personaplex-service
spec:
  ports:
  - name: ui
    port: 8998
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-personaplex
{{ if .Values.ingress.enabled }}
  type: ClusterIP
{{ else }}
  type: NodePort
{{ end }}
---
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-large-body@kubernetescrd"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-personaplex.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-personaplex-service
            port:
              number: 8998 # match internal port
        path: /
        pathType: Prefix
{{ end }}