hfTokenSecret: user-data

# Deployer Configuration
deployer:
  # Main deployer service configuration
  service:
    image:
      # repository: ghcr.io/kalavai-net/kalavai-deployer
      # tag: latest
      pullPolicy: Always
  # UI service configuration
  ui:
    image:
      # repository: ghcr.io/kalavai-net/kalavai-deployer-ui
      # tag: latest
      pullPolicy: Always
  memoryCapPercentage: 95
  # API Keys and external services configuration
  masterApiKey: null
  kalavaiApi:
    endpoint: null
    key: null
  gateway:
    ui_username: admin
    ui_password: null
    publicUrl: null
    internalUrl: null
    litellm_key: null

# Ingress Configuration
ingress:
  enabled: false
  subdomain: spaces.kalavai.net

# Autoscaling Configuration
autoscaling:
  enabled: false
  service:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 70
    targetMemoryUtilization: 80
  ui:
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilization: 70
    targetMemoryUtilization: 80

# System Configuration
system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null
  envFromSecrets: {}

