kalavaiApiImageTag: 0.8.17
kalavaiApiVersion: 0.1.19
kalavaiApiRingfenceNodeLabel: null
kalavaiApiRingfenceNodeLabelValue: null
kalavaiApiForcedNamespace: true
  
system:
  jobPriority: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
watcherImageTag: 2026.2.6
watcherVersion: 0.4.24
watcherAdminKey: admin_key
watcherReadonlyKey: readonly_key
watcherWriteKey: write_key

resourceQuota:
  enabled: false
  cpu: 4
  memory: "8Gi"
  nvidia: 0
  amd: 0

ui: 
  enabled: true