kalavaiApi:
  enabled: true
  forceCutoffMetricsDate: false
  imageTag: latest
  version: 0.1.21
  nodeSelector: null
  ringfenceNodeLabel: null
  ringfenceNodeLabelValue: null
  forcedNamespace: true
  forcedPriority: null

watcher:
  enabled: true
  imageTag: latest
  version: 0.4.25
  adminKey: admin_key
  readonlyKey: readonly_key
  writeKey: write_key

system:
  jobPriority: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR

ui: 
  enabled: true
  cpu: 1
  memory: 1.5