kalavaiApiImageTag: 0.8.17
kalavaiApiVersion: 0.1.20
kalavaiApiRingfenceNodeLabel: null
kalavaiApiRingfenceNodeLabelValue: null
kalavaiApiForcedNamespace: true
kalavaiApiForcedPriority: null

system:
  jobPriority: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
watcherImageTag: 2026.2.6
watcherVersion: 0.4.25
watcherAdminKey: admin_key
watcherReadonlyKey: readonly_key
watcherWriteKey: write_key

ui: 
  enabled: true