
version: "4.3.2"

singleuser:
  image:
    name: docker.io/cschranz/gpu-jupyter:v1.10_cuda-12.9_ubuntu-24.04_slim
    imagePullSecrets: null
  gpuCount: 1
  memory: 8
  cpu: 4
  storageCapacity: 4
  storageClass: "local-path"
  initScript: |
    #!/bin/bash

system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
