singleuser:
  username: user
  adminUsername: admin
  password: password
  image:
    cpu:
      name: ghcr.io/kalavai-net/jupyterhub-cpu:latest
    gpu:
      name: ghcr.io/kalavai-net/jupyterhub-cuda:latest
    imagePullSecrets: null
  storageClass: "local-path"
  initScript: |
    #!/bin/bash

distributed:
  enabled: false
  rayVersion: 2.52.0
  idleTimeoutSeconds: 60
  minGpus: 0
  maxGpus: 2
  pythonVersion: '312'
  cudaVersion: '128'

ingress:
  enabled: false
  subdomain: spaces.kalavai.net

system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null

resources:
  workerGpuMemory: null
  workingMemory: 5
  cpus: 2
  memory: 8
  gpus: 1