apiVersion: v1
stringData:
  watcherAdminKey: {{ .Values.watcher.adminKey }}
  watcherWriteKey: {{ .Values.watcher.writeKey }}
  watcherReadonlyKey: {{ .Values.watcher.readonlyKey }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true
