{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
    kalavai.job.name: {{ .Values.system.jobId}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
        kalavai.job.name: {{ .Values.system.jobId}}
    spec:
      containers:
        - name: kalavai-ui
          image: ghcr.io/kalavai-net/kalavai-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            {{- range $key, $value := .Values.system.envFromSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value }}
                  key: {{ $key }}
            {{- end }}
            - name: NEXT_PUBLIC_KALAVAI_API_URL
              value: http://{{ .Release.Name}}-api-service:8000
            - name: NEXT_PUBLIC_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                {{- if eq .Values.ui.accessKeyType "admin" }}
                  key: watcherAdminKey
                {{- else if eq .Values.ui.accessKeyType "write" }}
                  key: watcherWriteKey
                {{- else }}
                  key: watcherReadonlyKey
                {{- end }}
            - name: SHOW_RESOURCES
              value: "{{ .Values.ui.showResources }}"
            - name: SHOW_MONITORING
              value: "{{ .Values.ui.showMonitoring }}"
            - name: SHOW_USER_SPACES
              value: "{{ .Values.ui.showUserSpaces }}"
          resources:
            requests:
              cpu: {{ .Values.ui.cpu }}
              memory: {{ .Values.ui.memory }}Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui-service
  labels:
    app: {{ .Release.Name }}-ui
    kalavai.job.name: {{ .Values.system.jobId}}
spec:
  selector:
    app: {{ .Release.Name }}-ui
    kalavai.job.name: {{ .Values.system.jobId}}
  ports:
    - name: ui
      port: 80
      targetPort: 3000
  {{- if .Values.ingress.enabled }}
  type: ClusterIP
  {{- else }}
  type: NodePort
  {{- end }}
{{- end }}
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-large-body@kubernetescrd"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-pool-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-pool.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-ui-service
            port:
              number: 80 # match internal port
        path: /
        pathType: Prefix
{{- end }}