hfToken: null

resources:
  memory: 18
  cpus: 4
  gpus: 1
  gpuMemory: null
  imagePullPolicy: IfNotPresent

system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null
  envFromSecrets: []

ingress:
  enabled: false
  subdomain: spaces.kalavai.net