hfToken: null

resources:
  memory: 8
  cpus: 2
  gpus: 1
  gpuMemory: null
  imagePullPolicy: IfNotPresent

system:
  priorityClassName: user-spot-priority
  nodeSelectors: null
  nodeSelectorsOps: OR
  jobId: null

ingress:
  enabled: false
  subdomain: spaces.kalavai.net