# syntax=docker/dockerfile:1
FROM nvidia/cuda:13.2.0-cudnn-devel-ubuntu24.04 
#12.1.0-cudnn8-devel-ubuntu22.04

WORKDIR /workspace

# # install build dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv curl git cmake gcc g++ libgomp1 libbz2-dev libev-dev libffi-dev libgdbm-dev liblzma-dev libncurses-dev libreadline-dev libsqlite3-dev libssl-dev make tk-dev wget zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# install python dependencies
COPY common_requirements.txt .
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install -r common_requirements.txt --no-cache-dir

# Set virtual environment as default
ENV PATH="/opt/venv/bin:$PATH"
ENV PATH="/usr/local/cuda/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/lib64/stubs:$LD_LIBRARY_PATH"

# fetch llama.cpp source
WORKDIR /workspace
RUN git clone https://github.com/ggerganov/llama.cpp.git

COPY run_rpc_worker.sh .
COPY run_api_server.sh .
COPY build.sh .
COPY get_workers_address.sh .
COPY merge.sh .
COPY generate_config.py .

RUN chmod +x /workspace/merge.sh
RUN chmod +x /workspace/run_rpc_worker.sh
RUN chmod +x /workspace/run_api_server.sh
RUN chmod +x /workspace/build.sh
RUN chmod +x /workspace/get_workers_address.sh
