# TODO: https://github.com/ggml-org/llama.cpp/blob/master/.devops/rocm.Dockerfile

# syntax=docker/dockerfile:1
FROM rocm/dev-ubuntu-24.04:7.2.4

WORKDIR /workspace

# 1. Define the architectures you want to support
# Defaulting to 30-series (86) up to Blackwell (100/120) if supported
ARG GPU_TARGETS="gfx1100"

ENV DEBIAN_FRONTEND=noninteractive

# Install build dependencies
RUN apt update && \
    apt install -y python3 python3-pip python3-venv curl git cmake gcc g++ \
    libgomp1 libbz2-dev libev-dev libffi-dev libgdbm-dev liblzma-dev \
    libncurses-dev libreadline-dev libsqlite3-dev libssl-dev make tk-dev wget zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY common_requirements.txt .
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install -r common_requirements.txt --no-cache-dir

ARG LLAMACPP_VERSION=master

# Set environment paths
ENV PATH="/opt/venv/bin:/usr/local/cuda/bin:$PATH"

# Fetch and build llama.cpp
RUN git clone https://github.com/ggerganov/llama.cpp.git && \
    cd llama.cpp && \
    git checkout --detach ${LLAMACPP_VERSION} && \
    cmake -B build -DLLAMA_CURL=OFF -DGGML_HIP=ON -DGPU_TARGETS="${GPU_TARGETS}" -DCMAKE_BUILD_TYPE=Release -DLLAMA_BUILD_TESTS=OFF -DGGML_NATIVE=OFF && \
    cmake --build build --config Release -j $(nproc)

COPY run_rpc_worker.sh .
COPY run_api_server.sh .
COPY build.sh .
COPY get_workers_address.sh .
COPY merge.sh .
COPY generate_config.py .

RUN chmod +x /workspace/merge.sh
RUN chmod +x /workspace/run_rpc_worker.sh
RUN chmod +x /workspace/run_api_server.sh
RUN chmod +x /workspace/build.sh
RUN chmod +x /workspace/get_workers_address.sh
