# syntax=docker/dockerfile:1
#FROM debian:bullseye AS builder
FROM python:3.12-slim AS builder

ARG LLAMACPP_VERSION=master

WORKDIR /workspace

# Install build dependencies
RUN apt-get update && \
    apt-get install -y python3-venv curl git cmake gcc g++ \
    libgomp1 libbz2-dev libev-dev libffi-dev libgdbm-dev liblzma-dev \
    libncurses-dev libreadline-dev libsqlite3-dev libssl-dev make tk-dev wget zlib1g-dev && \
    rm -rf /var/lib/apt/lists/*

# Install python dependencies
COPY common_requirements.txt .
RUN python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install -r common_requirements.txt --no-cache-dir

# Set environment paths
ENV PATH="/opt/venv/bin:$PATH"

# Fetch and build llama.cpp
RUN git clone https://github.com/ggerganov/llama.cpp.git && \
    cd llama.cpp && \
    git checkout --detach ${LLAMACPP_VERSION} && \
    cmake -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DGGML_RPC=ON \
        -DGGML_BACKEND_DL=ON \
        -DGGML_CPU_ALL_VARIANTS=ON \
        -DLLAMA_CURL=OFF \
        -DLLAMA_BUILD_TESTS=OFF \
        -DGGML_NATIVE=OFF \
    && cmake --build build -j $(nproc)

COPY run_rpc_worker.sh .
COPY run_api_server.sh .
COPY build.sh .
COPY get_workers_address.sh .
COPY merge.sh .
COPY generate_config.py .

RUN chmod +x /workspace/merge.sh
RUN chmod +x /workspace/run_rpc_worker.sh
RUN chmod +x /workspace/run_api_server.sh
RUN chmod +x /workspace/build.sh
RUN chmod +x /workspace/get_workers_address.sh
