{{- if .Values.auth.enabled }}
apiVersion: v1
stringData:
  auth_token: {{ .Values.auth.token | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-raycluster-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true
{{- end }}
