# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-raycluster-service
#   labels:
#     # must have this!
#     kalavai.job.name: {{ .Values.system.jobId }}
# spec:
#   {{- if .Values.ingress.enabled }}
#   type: ClusterIP
#   {{- else }}
#   type: NodePort
#   {{- end }}
#   selector:
#     role: leader
#     kalavai.job.name: {{ .Values.system.jobId }}
#   ports:
#     # TODO: this port need gRPC access, traefik does not work, see: https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ingress-rayclient-tls.yaml
#     - name: client
#       port: 10001
#       targetPort: 10001
#     - name: dashboard
#       port: 8265
#       targetPort: 8265
#       protocol: TCP
#     - name: serve
#       port: 8000
#       targetPort: 8000
#       protocol: TCP
# ---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/enable-cors: "true"
    traefik.ingress.kubernetes.io/cors-allow-origin: "*"
    traefik.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    traefik.ingress.kubernetes.io/cors-allow-headers: "*"
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
  name: {{ .Release.Name }}-raycluster-ingress
spec:
  ingressClassName: traefik
  rules:
  # Dashboard (HTTP)
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-raycluster.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-raycluster-head-svc
            port:
              number: 8265 # Dashboard port
        path: /
        pathType: Prefix
  # Serve (HTTP)
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-raycluster-serve.{{ .Values.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-raycluster-head-svc
            port:
              number: 8000 # Serve port
        path: /
        pathType: Prefix
{{- end }}