apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: {{ .Release.Name}}
  labels:
    # must have this label
    kalavai.job.name: {{ .Values.system.jobId}}
spec:
  queue: default
  priorityClassName: {{ .Values.system.priorityClassName}}
  schedulerName: volcano
  plugins:
    env: []
    svc: ["--disable-network-policy=true"]
  maxRetry: 100000
  tasks:
  - replicas: 1   # One ps pod specified
    name: server
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of the ps pod
      metadata:
        labels:
          role: leader
          kalavai.job.name: {{ .Values.system.jobId}}
      spec:
        {{- if and .Values.deployment.githubUsername .Values.deployment.githubToken }}
        imagePullSecrets:
          - name: {{ .Release.Name }}-vllm-ghcr-secret
        {{- end }}
        terminationGracePeriodSeconds: 60
      {{- if eq .Values.deployment.gpuBackend "cuda" }}
        runtimeClassName: nvidia
      {{- end }}
        affinity:
        {{- if .Values.system.nodeAffinityPreferenceKey }}
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    kalavai.job.name: {{ .Values.system.jobId }}
                topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
        {{- end }}
        {{- if .Values.system.nodeSelectors }}
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {{ if eq .Values.system.nodeSelectorsOps "OR" }}
              {{ range $k, $v := .Values.system.nodeSelectors }}
              - matchExpressions:
                - key: {{$k}}
                  operator: In
                  values:
                  {{ range $v }}
                  - "{{ . }}"
                  {{ end }}
              {{ end }}
            {{ else }}
              - matchExpressions:
              {{ range $k, $v := .Values.system.nodeSelectors }}
                {{ range $v }}
                - key: {{ $k }}
                  operator: In
                  values:
                  - "{{ . }}"
                {{ end }}
              {{ end }}
            {{ end }}
        {{- end }}
        containers:
        - name: vllm-leader
          image: ghcr.io/kalavai-net/vllm-{{ .Values.deployment.gpuBackend}}:latest
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
          - sh
          - -c
          - |
          {{- if .Values.vllm.forceVersion }}
            echo "Forcing vllm version to {{ .Values.vllm.forceVersion }}";
            pip install vllm=={{ .Values.vllm.forceVersion }} --no-cache-dir;
          {{- else }}
            echo "Using auto-detected vllm version";
            pip show vllm;
          {{- end }}
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size={{ .Values.workers}} --ray_object_store_memory={{ .Values.deployment.sharedMemory}};
            sleep 30;
          {{- if eq .Values.deployment.gpuBackend "cuda" }}
            nvidia-smi;
          {{- else }}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {{- end }}
            ray status;
            # Run model
            echo "Total parallelism: {{ mul .Values.workers .Values.deployment.gpus }}";
            /home/ray/workspace/run_model.sh \
              --model_path="/home/ray/cache/{{ .Values.modelId }}" \
              --model_id={{ .Values.modelId}} \
              --model_name={{ .Values.deployment.modelNameOverride }} \
              --extra='{{ .Values.vllm.extra }}' \
              --template_url='{{ .Values.vllm.templateUrl }}' \
            {{- if .Values.deployment.autoParallelism }}
              --tensor_parallel_size={{ .Values.deployment.gpus }} \
              --pipeline_parallel_size={{ .Values.workers }} \
            {{- end}}
              --tool_call_parser={{ .Values.vllm.toolCallParser }} \
              --lora_modules="{{ .Values.vllm.loraModules }}";
            exit 1
          env:
          {{- if .Values.system.envFromSecrets }}
          {{- range .Values.system.envFromSecrets }}
          - name: {{ . }}
            valueFrom:
              secretKeyRef:
                name: {{ . }}
                key: {{ . }}
          {{- end }}
          {{- end }}
          {{-if .Values.hfToken }}
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name}}-vllm-secret
                key: hf_token
          {{- end }}
          - name: VLLM_ENGINE_READY_TIMEOUT_S
            value: "1200"
          - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
            value: "1200"
          - name: VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE
            value: "auto"
          - name: NCCL_DEBUG
            value: "{{ .Values.deployment.debugLevel }}"
          - name: VLLM_LOGGING_LEVEL
            value: "{{ .Values.deployment.debugLevel }}"
          - name: LMCACHE_CHUNK_SIZE
            value: "{{ .Values.lmcache.chunkSize}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{ .Values.lmcache.localCpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{ .Values.lmcache.maxLocalCpuSize}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{ .Values.lmcache.maxLocalDiskSize}}"
          - name: LMCACHE_REMOTE_URL
            value: {{ .Values.lmcache.remoteUrl}}
          - name: LMCACHE_LOCAL_DISK
            value: {{ .Values.lmcache.localDisk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          ports:
          - containerPort: 8080
            name: model-port
          - containerPort: 8265
            name: dashboard-port
          # this blocks internal traffic, which causes issues when tasks wait for each other
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.deployment.cpus}}
              memory: {{ .Values.deployment.memory }}Gi
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              nvidia.com/gpu: {{ .Values.deployment.gpus}}
            {{- else }}
              amd.com/gpu: {{ .Values.deployment.gpus}}
            {{- end }}
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              ephemeral-storage: {{ .Values.deployment.workingMemory}}Gi
            {{- end }}
            limits:
              cpu: {{ .Values.deployment.cpus}}
              memory: {{ add .Values.deployment.memory .Values.deployment.sharedMemory }}Gi
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              nvidia.com/gpu: {{ .Values.deployment.gpus}}
              {{- if .Values.deployment.gpuMemory }}
              nvidia.com/gpumem: {{ .Values.deployment.gpuMemory}}
              {{- end }}
            {{- else }}
              amd.com/gpu: {{ .Values.deployment.gpus}}
            {{- end }}
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              ephemeral-storage: {{ .Values.deployment.workingMemory}}Gi
            {{- end }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.deployment.sharedMemory }}Gi
        restartPolicy: {{ .Values.deployment.restartPolicy }}
  - replicas: {{ sub .Values.workers 1}}
    name: worker
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of worker pods
      metadata:
        labels:
          kalavai.job.name: {{ .Values.system.jobId}}
      spec:
        {{- if and .Values.deployment.githubUsername .Values.deployment.githubToken }}
        imagePullSecrets:
          - name: {{ .Release.Name }}-vllm-ghcr-secret
        {{- end }}
        terminationGracePeriodSeconds: 60
      {{- if eq .Values.deployment.gpuBackend "cuda" }}
        runtimeClassName: nvidia
      {{- end }}
        affinity:
        {{- if .Values.system.nodeAffinityPreferenceKey }}
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    kalavai.job.name: {{ .Values.system.jobId }}
                topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
        {{- end }}
        {{- if .Values.system.nodeSelectors }}
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {{ if eq .Values.system.nodeSelectorsOps "OR" }}
              {{ range $k, $v := .Values.system.nodeSelectors }}
              - matchExpressions:
                - key: {{$k}}
                  operator: In
                  values:
                  {{ range $v }}
                  - "{{ . }}"
                  {{ end }}
              {{ end }}
            {{ else }}
              - matchExpressions:
              {{ range $k, $v := .Values.system.nodeSelectors }}
                {{ range $v }}
                - key: {{ $k }}
                  operator: In
                  values:
                  - "{{ . }}"
                {{ end }}
              {{ end }}
            {{ end }}
        {{- end }}
        containers:
        - name: vllm-worker
          image: ghcr.io/kalavai-net/vllm-{{ .Values.deployment.gpuBackend}}:latest
          imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
          command:
          - sh
          - -c
          - |
          {{- if .Values.vllm.forceVersion }}
            echo "Forcing vllm version to {{ .Values.vllm.forceVersion }}";
            pip install vllm=={{ .Values.vllm.forceVersion }} --no-cache-dir;
          {{- else }}
            echo "Using auto-detected vllm version";
            pip show vllm;
          {{- end }}
            PS_HOST=`cat /etc/volcano/server.host`;
          {{- if eq .Values.deployment.gpuBackend "cuda" }}
            nvidia-smi;
          {{- else }}
            rocm-smi;
            python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
          {{- end }}
            RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$PS_HOST --ray_port=6379 --ray_object_store_memory={{ .Values.deployment.sharedMemory}} --ray_block=1
          env:
          {{- range $key, $value := .Values.system.env }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name}}-svllm-ecret
                key: hf_token
          - name: VLLM_ENGINE_READY_TIMEOUT_S
            value: "1200"
          - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
            value: "1200"
          - name: VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE
            value: "auto"
          - name: NCCL_DEBUG
            value: "{{ .Values.deployment.debugLevel }}"
          - name: VLLM_LOGGING_LEVEL
            value: "{{ .Values.deployment.debugLevel }}"
          - name: LMCACHE_CHUNK_SIZE
            value: "{{ .Values.lmcache.chunkSize}}"
          - name: LMCACHE_LOCAL_CPU
            value: "{{ .Values.lmcache.localCpu}}"
          - name: LMCACHE_MAX_LOCAL_CPU_SIZE
            value: "{{ .Values.lmcache.maxLocalCpuSize}}"
          - name: LMCACHE_MAX_LOCAL_DISK_SIZE
            value: "{{ .Values.lmcache.maxLocalDiskSize}}"
          - name: LMCACHE_REMOTE_URL
            value: {{ .Values.lmcache.remoteUrl}}
          - name: LMCACHE_LOCAL_DISK
            value: {{ .Values.lmcache.localDisk}}
          # - name: HSA_OVERRIDE_GFX_VERSION
          #   value: "10.3.0"
          resources:
            requests:
              cpu: {{ .Values.deployment.cpus}}
              memory: {{ .Values.deployment.memory}}Gi
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              nvidia.com/gpu: {{ .Values.deployment.gpus}}
            {{- else }}
              amd.com/gpu: {{ .Values.deployment.gpus}}
            {{- end }}
              ephemeral-storage: {{ .Values.deployment.workingMemory}}Gi
            limits:
              cpu: {{ .Values.deployment.cpus}}
              memory: {{ add .Values.deployment.memory .Values.deployment.sharedMemory}}Gi
            {{- if eq .Values.deployment.gpuBackend "cuda" }}
              nvidia.com/gpu: {{ .Values.deployment.gpus}}
              {{- if .Values.deployment.gpuMemory }}
              nvidia.com/gpumem: {{ .Values.deployment.gpuMemory}}
              {{- end }}
            {{- else }}
              amd.com/gpu: {{ .Values.deployment.gpus}}
            {{- end }}
              ephemeral-storage: {{ .Values.deployment.workingMemory}}Gi
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - name: cache
              mountPath: /home/ray/cache
        volumes:
        - name: cache
          emptyDir: {}
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.deployment.sharedMemory}}Gi
        restartPolicy: {{ .Values.deployment.restartPolicy }}
  {{ if .Values.litellm.enabled }}
  - replicas: 1
    name: registrar
    policies:
    - event: PodEvicted
      action: RestartJob
    - event: PodFailed
      action: RestartJob
    - event: TaskCompleted
      action: RestartJob
    - event: Unknown
      action: RestartJob
    template: # Definition of worker pods
      metadata:
        labels:
          kalavai.job.name: {{ .Values.system.jobId}}
      spec:
        terminationGracePeriodSeconds: 60
      {{- if .Values.system.nodeSelectors }}
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
            {{- if eq .Values.system.nodeSelectorsOps "OR" }}
              {{- range $k, $v := .Values.system.nodeSelectors }}
              - matchExpressions:
                - key: {{$k}}
                  operator: In
                  values:
                  {{- range $v }}
                  - "{{ . }}"
                  {{- end }}
              {{- end }}
            {{- else }}
              - matchExpressions:
              {{- range $k, $v := .Values.system.nodeSelectors }}
                {{- range $v }}
                - key: {{ $k }}
                  operator: In
                  values:
                  - "{{ . }}"
                {{- end }}
              {{- end }}
            {{- end }}
        {{- end }}
        containers:
        - name: registrar-leader
          image: ghcr.io/kalavai-net/kalavai-utils:latest
          command:
          - sh
          - -c
          - |
            echo "Waiting for model to be served..."
            echo "Namespace: "$VC_NAMESPACE;
            PS_HOST=`cat /etc/volcano/server.host`;
            {{ if .Values.litellm.waitReady }}
            /workspace/wait_for_service.sh --servers="$PS_HOST" --port=8080
            {{ end }}
            export MODEL_API_BASE="http://"$PS_HOST"."$VC_NAMESPACE":8080/v1";
            /workspace/start_point.sh \
              --litellm_kalavai_extras='{{ .Values.litellm.kalavaiExtras }}' \
              --litellm_access_group={{ .Values.litellm.accessGroup }}
          env:
          {{- range $key, $value := .Values.system.envFromSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value }}
                key: {{ $key }}
          {{- end }}
          - name: VC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LITELLM_MODEL_NAME
          {{ if .Values.deployment.modelNameOverride }}
            value: "{{ .Values.deployment.modelNameOverride }}"
          {{ else }}
            value: "{{ .Values.modelId }}"
          {{ end }}
          {{- if .Values.litellm.baseUrl}}
          - name: LITELLM_BASE_URL
            value: {{ .Values.litellm.baseUrl }}
          {{- end }}
          {{- if .Values.litellm.baseUrl}}
          - name: LITELLM_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-vllm-secret
                key: litellm_key
          {{- end }}
          - name: MODEL_ID
            value: {{ .Values.modelId }}
          - name: DEPLOYMENT_ID
            value: {{ .Release.Name }}
          - name: PROVIDER
            value: hosted_vllm
          lifecycle:
            preStop:
              exec:
                command: 
                - sh
                - -c
                - |
                  /workspace/cleanup.sh
          resources:
            requests:
              cpu: 0.05
              memory: 0.05Gi
            limits:
              cpu: 0.05
              memory: 0.05Gi
        restartPolicy: Always
  {{- end }}