apiVersion: v1
stringData:
  hf_token: {{ .Values.hfToken }}
  {{- if .Values.litellm.enabled }}
  litellm_key: {{ .Values.litellm.key }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-vllm-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: Opaque
immutable: true
---
{{- if and .Values.vllm.githubUsername .Values.vllm.githubToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-vllm-ghcr-secret
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
type: kubernetes.io/dockerconfigjson
stringData:
  # We generate the JSON structure here so you don't have to base64 it manually
  .dockerconfigjson: |
    {
      "auths": {
        "https://ghcr.io": {
          "username": {{ .Values.vllm.githubUsername | default "" | quote }},
          "password": {{ .Values.vllm.githubToken | default "" | quote }},
          "auth": "{{ printf "%s:%s" (.Values.vllm.githubUsername | default "") (.Values.vllm.githubToken | default "") | b64enc }}"
        }
      }
    }
immutable: true
{{- end }}