apiVersion: kalavai.net/v1
kind: ServerWorkerSet
metadata:
  name: {{ .Release.Name }}-vllm
spec:
  replicas: {{ .Values.system.replicas }}
  workersPerInstance: {{ sub .Values.system.workers 1 }}
  labels:
    kalavai.job.name: {{ .Values.system.jobId}}
    {{- if .Values.system.workerGpuMemory }}
    kalavai/vram: {{ .Values.system.workerGpuMemory | quote }}
    {{- end }}
  service:
    name: {{ .Release.Name }}-vllm-service
    port: 8080
    targetPort: 8080
    stickySession: {{ .Values.service.stickySession }}
    stickySessionTimeoutSeconds: {{ .Values.service.stickySessionTimeoutSeconds }}
  {{- if .Values.service.ingress.enabled }}
    type: ClusterIP
  {{- else }}
    type: NodePort
  {{- end }}  
  autoScaling:
    enabled: {{ .Values.autoscaling.enabled }}
  {{- if .Values.autoscaling.enabled }}   
    hosts:
      - {{ .Release.Name }}-{{ .Release.Namespace }}-vllm.{{ .Values.service.ingress.subdomain }}    
    pathPrefixes:
      - "/"              
    replicas:
      min: {{ .Values.autoscaling.minReplicas }}        
      max: {{ .Values.autoscaling.maxReplicas }}
    scaledownPeriod: 300
    scalingMetric:
      requestRate:
        granularity: 1s
        targetValue: 1
        window: 1m
      # concurrency:
      #   targetValue: 10
  {{- end }}
{{- if .Values.litellm.enabled }}
  initHook:
    # Used for model registration
    spec:
      containers:
      - name: registrar-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. register model
          echo "REGISTER MODEL WITH GATEWAY..."
        {{- if .Values.litellm.waitReady }}
          echo "Waiting for model service to be up..."
          /workspace/wait_for_service.sh --servers="$GLOBAL_SERVICE_ADDRESS" --port=$GLOBAL_SERVICE_PORT
        {{- end }}
          export MODEL_API_BASE="http://$GLOBAL_SERVICE_ADDRESS:$GLOBAL_SERVICE_PORT/v1";
          /workspace/start_point.sh \
            --litellm_kalavai_extras='{{ .Values.litellm.kalavaiExtras }}' \
            --litellm_access_group={{ .Values.litellm.accessGroup }}
        env:
        - name: LITELLM_MODEL_NAME
        {{- if .Values.litellm.modelNameOverride }}
          value: "{{ .Values.litellm.modelNameOverride }}"
        {{- else }}
          value: "{{ .Values.modelId }}"
        {{- end }}
        - name: LITELLM_BASE_URL
          value: {{ .Values.litellm.baseUrl }}
        - name: LITELLM_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-vllm-secret
              key: litellm_key
        - name: MODEL_ID
          value: "{{ .Values.modelId }}"
        - name: DEPLOYMENT_ID
          value: {{ .Release.Name }}
        - name: PROVIDER
          value: {{ .Values.litellm.provider }}
  finalizerHook:
    # Used for model deregistration
    spec:
      containers:
      - name: registrar-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. deregister model
          /workspace/cleanup.sh
        env:
        - name: LITELLM_BASE_URL
          value: {{ .Values.litellm.baseUrl }}
        # secret may be deleted before this is run, so hardcode the key
        - name: LITELLM_KEY
          value: {{ .Values.litellm.key }}
        - name: DEPLOYMENT_ID
          value: {{ .Release.Name }}
{{- end }}
  server:
    spec:
      metadata:
        labels:
          billing: {{ .Values.billing.enabled | quote }}
      terminationGracePeriodSeconds: 60
    {{- if eq .Values.system.backend "cuda" }}
      runtimeClassName: nvidia
    {{- end }}
      affinity:
      {{- if .Values.system.nodeAffinityPreferenceKey }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  kalavai.job.name: {{ .Values.system.jobId }}
              topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
      {{- end }}
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{ if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{ range $v }}
                - "{{ . }}"
                {{ end }}
            {{ end }}
          {{ else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{ end }}
      {{- end }}
      {{- if .Values.billing.enabled }}
      serviceAccountName: kalavai-downstream-api-reader-sa
      {{- end }}
      containers:
      - name: vllm-leader
        image: ghcr.io/kalavai-net/vllm-{{ .Values.system.backend}}:{{ .Values.vllm.image.tag }}
        imagePullPolicy: {{ .Values.vllm.imagePullPolicy }}
        command:
        - sh
        - -c
        - |
        {{- if .Values.vllm.forceVersion }}
          echo "Forcing vllm version to {{ .Values.vllm.forceVersion }}";
          pip install vllm=={{ .Values.vllm.forceVersion }} --no-cache-dir;
        {{- else }}
          echo "Using auto-detected vllm version";
          pip show vllm;
        {{- end }}
        {{- if gt (int .Values.system.workers) 1 }}
          RAY_memory_usage_threshold=0.99 RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh leader --ray_cluster_size={{ .Values.system.workers}} --ray_object_store_memory=1;
          sleep 30;
        {{- else }}
          echo "Skipping ray init"
        {{- end }}
        {{- if eq .Values.system.backend "cuda" }}
          nvidia-smi;
        {{- else }}
          rocm-smi;
          python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
        {{- end }}
          ray status;
          # Run model
          echo "Total parallelism: {{ mul .Values.system.workers .Values.system.gpus }}";
          /home/ray/workspace/run_model.sh \
          {{- if .Values.vllm.modelNameOverride }}
            --model_name={{ .Values.vllm.modelNameOverride }} \
          {{- end }}
          {{- if .Values.lmcache.enabled }}
            --extra='{{ .Values.vllm.extra }} --no-disable-hybrid-kv-cache-manager --kv-transfer-config {{ .Values.lmcache.kvTransferConfig }}' \
          {{- else }}
            --extra='{{ .Values.vllm.extra }}' \
          {{- end }}
          {{- if .Values.vllm.templateUrl }}
            --template_url='{{ .Values.vllm.templateUrl }}' \
          {{- end }}
          {{- if .Values.vllm.autoParallelism}}
            --tensor_parallel_size={{ .Values.system.gpus }} \
            --pipeline_parallel_size={{ .Values.system.workers }} \
          {{- end}}
          {{- if .Values.vllm.loraModules }}
            --lora_modules="{{ .Values.vllm.loraModules }}";
          {{- end }}
            --model_path="/home/ray/cache/{{ .Values.modelId }}" \
            --model_id={{ .Values.modelId}};
          exit 1
        env:
        {{- range $key, $value := .Values.system.envFromSecrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $value }}
              key: {{ $key }}
        {{- end }}
        {{- if .Values.hfToken }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name}}-vllm-secret
              key: hf_token
        {{- end }}
        - name: VLLM_ENGINE_READY_TIMEOUT_S
          value: "1200"
        - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
          value: "1200"
        - name: VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE
          value: "auto"
        - name: NCCL_DEBUG
          value: "{{ .Values.vllm.debugLevel }}"
        - name: VLLM_LOGGING_LEVEL
          value: "{{ .Values.vllm.debugLevel }}"
        # LMCACHE config https://docs.lmcache.ai/api_reference/configurations.html
      {{- if .Values.lmcache.enabled }}
        - name: LMCACHE_USE_EXPERIMENTAL
          value: "True"
        - name: LMCACHE_CHUNK_SIZE
          value: "{{ .Values.lmcache.chunkSize}}"
        {{- if .Values.lmcache.remoteUrl}}
        - name: LMCACHE_REMOTE_URL
          value: {{ .Values.lmcache.remoteUrl}}
        {{- end }}
        {{- if .Values.lmcache.localCpu}}
        - name: LMCACHE_MAX_LOCAL_CPU_SIZE
          value: "{{ .Values.lmcache.maxLocalCpuSize}}"
        - name: LMCACHE_LOCAL_CPU
          value: "true"
        {{- end }}
        {{- if .Values.lmcache.localDisk}}
        - name: LMCACHE_MAX_LOCAL_DISK_SIZE
          value: "{{ .Values.lmcache.maxLocalDiskSize}}"
        - name: LMCACHE_LOCAL_DISK
          value: {{ .Values.lmcache.localDisk}}
        {{- end }}
      {{- end }}
        ports:
        - containerPort: 8080
          name: model-port
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: {{ .Values.system.gpus }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: {{ .Values.system.gpus }}
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
          limits:
            cpu: {{ .Values.system.cpus}}
            memory: {{ add .Values.system.memory .Values.vllm.sharedMemory }}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: {{ .Values.system.gpus }}
            # {{ if .Values.system.workerGpuMemory }}
            # nvidia.com/gpumem: {{ .Values.system.workerGpuMemory}}
            # {{ end }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: {{ .Values.system.gpus }}
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
    {{- if .Values.billing.enabled }}  
      - name: billing-sidecar
        image: ghcr.io/kalavai-net/kalavai-registrar:latest
        imagePullPolicy: Always
        command:
        - sh
        - -c
        - |
          # 1. Fetch node Info
          echo "FETCH NODE INFO..."
          PROVIDER=$(python3 get_node_label_value.py --in-cluster --node-name $NODE_NAME --label-key kalavai/region)
          GPU_TYPE=$(python3 get_node_label_value.py --in-cluster --node-name $NODE_NAME --label-key kalavai/instance)
          echo "PROVIDER: $PROVIDER"
          echo "GPU_TYPE: $GPU_TYPE"

          # 2. Wait for model to be ready
          echo "WAIT FOR MODEL TO BE READY at $GLOBAL_SERVICE_ADDRESS:$GLOBAL_SERVICE_PORT..."
          /workspace/wait_for_service.sh --servers="$GLOBAL_SERVICE_ADDRESS" --port=$GLOBAL_SERVICE_PORT

          # 3. start heartbeat
          # VRAM USAGE / minute = billingInterval(mins) * gpuMemPerWorker  * NumWorkers
          {{- $vramUsage := mul (mul .Values.billing.interval .Values.system.workerGpuMemory) .Values.system.workers }}
          {{- $cpuUsage := mul (mul .Values.billing.interval .Values.system.cpus) .Values.system.workers }}
          {{- $memoryUsage := mul (mul .Values.billing.interval .Values.system.memory) .Values.system.workers }}
          VRAM_USAGE={{ $vramUsage }}
          CPU_USAGE={{ $cpuUsage }}
          MEMORY_USAGE={{ $memoryUsage }}
          JOB_ID={{ .Values.system.jobId }}
          echo "START HEARTBEAT..."
          python3 usage_event_generator.py
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: USER_ID
          value: {{ .Values.billing.userId }}
        - name: INTERVAL_SECONDS
          value: {{ .Values.billing.interval | quote }}
        resources:
          requests:
            cpu: 0.05
            memory: 64Mi
          limits:
            cpu: 0.1
            memory: 128Mi
    {{- end }}
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: {{ .Values.vllm.sharedMemory }}Gi
      restartPolicy: {{ .Values.vllm.restartPolicy }}
    policy:
    - event: PodFailed
      action: RestartInstance
    - event: OOMKilled
      action: RestartInstance
    - event: PodEvicted
      action: RestartInstance
    - event: Unknown
      action: RestartInstance
  worker:
    spec:
      terminationGracePeriodSeconds: 60
    {{- if eq .Values.system.backend "cuda" }}
      runtimeClassName: nvidia
    {{- end }}
      affinity:
      {{- if .Values.system.nodeAffinityPreferenceKey }}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  kalavai.job.name: {{ .Values.system.jobId }}
              topologyKey: {{ .Values.system.nodeAffinityPreferenceKey }}
      {{- end }}
      {{- if .Values.system.nodeSelectors }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
          {{ if eq .Values.system.nodeSelectorsOps "OR" }}
            {{ range $k, $v := .Values.system.nodeSelectors }}
            - matchExpressions:
              - key: {{$k}}
                operator: In
                values:
                {{ range $v }}
                - "{{ . }}"
                {{ end }}
            {{ end }}
          {{ else }}
            - matchExpressions:
            {{ range $k, $v := .Values.system.nodeSelectors }}
              {{ range $v }}
              - key: {{ $k }}
                operator: In
                values:
                - "{{ . }}"
              {{ end }}
            {{ end }}
          {{ end }}
      {{- end }}
      containers:
      - name: vllm-worker
        image: ghcr.io/kalavai-net/vllm-{{ .Values.system.backend}}:{{ .Values.vllm.image.tag }}
        imagePullPolicy: {{ .Values.vllm.imagePullPolicy }}
        command:
        - sh
        - -c
        - |
        {{- if .Values.vllm.forceVersion }}
          echo "Forcing vllm version to {{ .Values.vllm.forceVersion }}";
          pip install vllm=={{ .Values.vllm.forceVersion }} --no-cache-dir;
        {{- else }}
          echo "Using auto-detected vllm version";
          pip show vllm;
        {{- end }}
        {{- if eq .Values.system.backend "cuda" }}
          nvidia-smi;
        {{- else }}
          rocm-smi;
          python -c "import torch; print(torch.cuda.device_count(), torch.cuda.get_device_name(0))";
        {{- end }}
          echo "Connecting to server at $SERVER_ADDRESS"
          RAY_memory_usage_threshold=0.99 RAY_BACKEND_LOG_LEVEL=error /home/ray/workspace/ray_init.sh worker --ray_address=$SERVER_ADDRESS --ray_port=6379 --ray_object_store_memory=1 --ray_block=1
        env:
        {{- range $key, $value := .Values.system.envFromSecrets }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ $value }}
              key: {{ $key }}
        {{- end }}
        {{- if .Values.hfToken }}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name}}-vllm-secret
              key: hf_token
        {{- end }}
        - name: VLLM_ENGINE_READY_TIMEOUT_S
          value: "1200"
        - name: VLLM_ENGINE_ITERATION_TIMEOUT_S
          value: "1200"
        - name: VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE
          value: "auto"
        - name: NCCL_DEBUG
          value: "{{ .Values.vllm.debugLevel }}"
        - name: VLLM_LOGGING_LEVEL
          value: "{{ .Values.vllm.debugLevel }}"
        # LMCACHE config https://docs.lmcache.ai/api_reference/configurations.html
      {{- if .Values.lmcache.enabled }}
        - name: LMCACHE_USE_EXPERIMENTAL
          value: "True"
        - name: LMCACHE_CHUNK_SIZE
          value: "{{ .Values.lmcache.chunkSize}}"
        {{- if .Values.lmcache.remoteUrl}}
        - name: LMCACHE_REMOTE_URL
          value: {{ .Values.lmcache.remoteUrl}}
        {{- end }}
        {{- if .Values.lmcache.localCpu}}
        - name: LMCACHE_MAX_LOCAL_CPU_SIZE
          value: "{{ .Values.lmcache.maxLocalCpuSize}}"
        - name: LMCACHE_LOCAL_CPU
          value: "true"
        {{- end }}
        {{- if .Values.lmcache.localDisk}}
        - name: LMCACHE_MAX_LOCAL_DISK_SIZE
          value: "{{ .Values.lmcache.maxLocalDiskSize}}"
        - name: LMCACHE_LOCAL_DISK
          value: {{ .Values.lmcache.localDisk}}
        {{- end }}
      {{- end }}
        resources:
          requests:
            cpu: {{ .Values.system.cpus}}
            memory: {{ .Values.system.memory}}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: {{ .Values.system.gpus }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: {{ .Values.system.gpus }}
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
          limits:
            cpu: {{ .Values.system.cpus}}
            memory: {{ add .Values.system.memory .Values.vllm.sharedMemory }}Gi
          {{ if eq .Values.system.backend "cuda" }}
            nvidia.com/gpu: {{ .Values.system.gpus }}
            # {{ if .Values.system.workerGpuMemory }}
            # nvidia.com/gpumem: {{ .Values.system.workerGpuMemory}}
            # {{ end }}
          {{ else if eq .Values.system.backend "rocm" }}
            amd.com/gpu: {{ .Values.system.gpus }}
          {{ end }}
            ephemeral-storage: {{ .Values.system.workingMemory}}Gi
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.vllm.sharedMemory }}Gi
      restartPolicy: {{ .Values.vllm.restartPolicy }}
    policy:
    - event: PodFailed
      action: ReplacePod
    - event: OOMKilled
      action: ReplacePod
    - event: OOMKilled
      action: ReplacePod
    - event: PodEvicted
      action: ReplacePod
    - event: Unknown
      action: ReplacePod
---
{{- if .Values.service.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-vllm-ingress
  labels:
    kalavai.job.name: {{ .Values.system.jobId }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}-vllm.{{ .Values.service.ingress.subdomain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-vllm-service
            port:
              number: 8080 # match internal port
        path: /
        pathType: Prefix
{{- end }}